
// auto-generated by do_default_opengl_shaders.py

// clang-format off
#pragma once
#define OPENGL_STRINGIFY(x)      #x


std::string fontVertSrc = OPENGL_STRINGIFY(
uniform mat4 mvp;

in vec4 Position;
in vec2 TexCoord;

uniform lowp vec4 color;

out vec2 texCoordV;

void main() {
	texCoordV	= TexCoord;
	gl_Position = mvp * Position;
}
);
std::string fontFragSrc = OPENGL_STRINGIFY(

uniform lowp vec4 color;
in vec2 texCoordV;
out vec4 fragColor;
uniform sampler2D myTextureSampler;

void main() {
    fragColor = color;
    fragColor.a *= texture(myTextureSampler, texCoordV).a;
}
);

std::string nothingVertSrc = OPENGL_STRINGIFY(
uniform mat4 mvp;

in vec4 Position;
uniform lowp vec4 color;
out lowp vec4 colorV;

void main() {
	colorV		= color;
	gl_Position = mvp * Position;
}
);
std::string nothingFragSrc = OPENGL_STRINGIFY(
in lowp vec4 colorV;
out vec4 fragColor;

void main() {
    fragColor = colorV;
}
);

std::string texVertSrc = OPENGL_STRINGIFY(

uniform mat4 mvp;

in vec4 Position;
in lowp vec2 TexCoord;
uniform lowp vec4 color;

out lowp vec4 colorV;
out lowp vec2 texCoordV;
void main() {
	colorV		= color;
	texCoordV	= TexCoord;
	gl_Position = mvp * Position;
}
);
std::string texFragSrc = OPENGL_STRINGIFY(
in lowp vec4 colorV;
in lowp vec2 texCoordV;
out vec4 fragColor;
uniform sampler2D myTextureSampler;

void main() {
    fragColor = texture(myTextureSampler, texCoordV) * colorV;
}
);

std::string colorVertSrc = OPENGL_STRINGIFY(
uniform mat4 mvp;
uniform lowp vec4 color;

in vec4 Position;
in lowp vec4 Color;

out lowp vec4 colorV;

void main() {
	colorV		= Color * color;
	gl_Position = mvp * Position;
}
);
std::string colorFragSrc = OPENGL_STRINGIFY(
in lowp vec4 colorV;
out vec4 fragColor;

void main() {
    fragColor = colorV;
}
);

std::string colorTextureVertSrc = OPENGL_STRINGIFY(
uniform mat4 mvp;

in vec4 Position;
in lowp vec2 TexCoord;
in lowp vec4 Color;

out lowp vec4 colorV;
out lowp vec2 texCoordV;
void main() {
	colorV		= Color;
	texCoordV	= TexCoord;
	gl_Position = mvp * Position;
}
);
std::string colorTextureFragSrc = OPENGL_STRINGIFY(
in lowp vec4 colorV;
in lowp vec2 texCoordV;
out vec4 fragColor;
uniform sampler2D myTextureSampler;

void main() {
	fragColor = texture(myTextureSampler, texCoordV) * colorV;
}
);

// clang-format on
