if (APPLE)

  if (NOT BUILD_PLATFORM_IS_IOS)
    add_compile_definitions (GL_SILENCE_DEPRECATION __MACOSX_CORE__ MZGL_GL2)
    list (APPEND MZGL_LIBRARIES "-framework AppKit")
    list (APPEND MZGL_LIBRARIES "-framework AudioUnit")
    list (APPEND MZGL_LIBRARIES "-framework OpenGL")
  endif ()

  list (APPEND MZGL_LIBRARIES "-framework Accelerate")
  list (APPEND MZGL_LIBRARIES "-framework StoreKit")
  list (APPEND MZGL_LIBRARIES "-framework CoreVideo")
  list (APPEND MZGL_LIBRARIES "-framework CoreMidi")
  list (APPEND MZGL_LIBRARIES "-framework CoreAudio")
  list (APPEND MZGL_LIBRARIES "-framework AVFoundation")
  list (APPEND MZGL_LIBRARIES "-framework CoreMedia")
  list (APPEND MZGL_LIBRARIES "-framework WebKit")
  list (APPEND MZGL_LIBRARIES "-framework CoreAudioKit")
  list (APPEND MZGL_LIBRARIES "-framework UniformTypeIdentifiers")

  set_source_files_properties (lib/mzgl/app/apple/AUv3/MZGLEffectAU.mm PROPERTIES COMPILE_FLAGS "-fobjc-arc")

  mzgl_compile_as_objc (lib/mzgl/App.cpp)
  mzgl_compile_as_objc (lib/mzgl/util/Dialogs.cpp)
  mzgl_compile_as_objc (lib/mzgl/util/util.cpp)
  mzgl_compile_as_objc (lib/mzgl/audio/AudioFileApple.cpp)
  mzgl_compile_as_objc (lib/mzgl/util/log.cpp)
  mzgl_compile_as_objc (lib/mzgl/net/netUtil.cpp)
  mzgl_compile_as_objc (lib/mzgl/util/Haptics.cpp)
endif ()
