include(${CMAKE_CURRENT_LIST_DIR}/print.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/log-saver.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/warning-saver.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/package-manager.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/cpm.cmake)
