function(mzgl_supress_target_warnings TARGET)
  mzgl_print_in_red("[WARNINGS] -> Supressed in ${TARGET}")
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|AppleClang")
    target_compile_options("${TARGET}" PRIVATE -w)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    target_compile_options("${TARGET}" PRIVATE -w)
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    target_compile_options("${TARGET}" PRIVATE /w)
  else()
    message(WARNING "Unknown compiler. Warnings suppression not applied.")
  endif()
endfunction(mzgl_supress_target_warnings)

function(mzgl_supress_warnings)
  # PortAudio is only built on Linux and Windows (see CMakeLists.txt).
  if(TARGET PortAudio)
    mzgl_supress_target_warnings(PortAudio)
  endif()
endfunction()
